### ISSUE TITLE
FastBuildMonitor works brielfy at first, then stops working

### ISSUE THREAD

**Issue by missmah** [yass007/FASTBuildMonitor#10]
![fastbuildmonitor](https://cloud.githubusercontent.com/assets/10825214/21168116/8a3ebeb8-c17f-11e6-909f-babcf9c9e65f.png)

FastBuildMonitor is working, but only for a moment per build...

Running a command like this, from within the FastBuild\Code directory (attempting to build FastBuild itself as a test case): C:\FastBuild\FBuild.exe -dist -clean -monitor -summary

What happens, is that for a moment at the beginning of the build, FastBuildMonitor seems to work. And then, it quickly stops working. The build continues for roughly a minute, but FastBuildMonitor doesn't show any more progress updates visually.

The next time I start another build, the same behavior happens (a burst of activity, followed by nothing for the rest of the build).

At the same time, I'm having an issue with -dist not being able to distribute the build for some reason. I suspect these issues may be related; but, have yet to track down the issue.

**Comment by yass007** [comment]
Hello!

Could you attach the file that's in: C:\Users\<username>\AppData\Local\Temp\FastBuild\FastBuildLog.log ?

From what I can see, the FBuild.exe process properly started and finished its session, so your log file should contain both START and STOP events:
131262306509240000 START_BUILD 1 18416
....
131262307091620000 STOP_BUILD

However what's weird is the Orange bars on the graph which indicate network timeouts.
So we should be able to find somewhere in the logs:
FINISH_JOB TIMEOUT

Are you seeing that?

I briefly tried to compile FBuild v0.92 itself with the distributed binary and it works fine.
I tried it without distribution though, I'll try it with -dist when I'm at home.

When you say that the build continues after it had stopped, can you verify if we are talking about the same FBuild.exe process instance or another one that is spawned ?

I'm asking that because it's unlikely that the same process builds anything after FLog::StopBuild() is called...

**Comment by missmah** [comment]
Hi! And thanks for the informative response!

The log is not quite as expected:
[FastBuildLog.txt](https://github.com/yass007/FASTBuildMonitor/files/659609/FastBuildLog.txt)

It's curious because the local indicates "local" for everything - despite the command line invoking the build having been -dist.

I'm wondering if the log was overwritten by a "local" build after the initial "dist" build failed due to network timeout, as you suspected?

**Comment by yass007** [comment]
Thanks for sending the log!

It looks like the logs are healthy and there are no timeouts/errors.
I suspect that the dll version you are running with is outdated. I had to change the parsing format before the monitor became officially suported by FB...

I have tested your log file and it shows ok (attached).

Could you install the latest vsix (https://github.com/yass007/FASTBuildMonitor/releases/tag/v1.0) and let me know if you are able to repro the issue ?

Thanks!
![fastbuildmonitorsh](https://cloud.githubusercontent.com/assets/2611324/21300466/36487000-c572-11e6-81d7-5451a5f2167e.png)

**Comment by yass007** [comment]
Hi @missmah, is this issue still occurring or can I just close it ?
Thanks!

**Comment by missmah** [comment]
Hey @yass007, we fixed our issue by updating our build of fastbuild to cherry pick latest of some files which we had previously gotten from the dev branch from their newer versions in the master branch. I'm not exactly sure which bit of code it was, but something seemed to be getting in the way of monitor working.

It's been working great for a while, so definitely lets close this issue. :)

Thanks again for the help!
