### ISSUE TITLE
Window takes a very long time to appear when it's currently hidden

### ISSUE THREAD

**Issue by jairbubbles** [yass007/FASTBuildMonitor#2]
I attached FASTBuild Monitor into the bottom panel:
![2016-08-24 14_13_25-scimitar tool dll win64 vs2012 - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/15875066/17930144/07b7207e-6a05-11e6-9df6-5935263719cc.png)
When I got to output and switch back to FASTBuild Monitor it takes several seconds (around 10) for the windows to appear.

**Comment by yass007** [comment]
Thanks for reporting this.
Is it happening when you open the FB Monitor tab/window for the very first time? or every time you hide it and try to reopen it again?

**Comment by jairbubbles** [comment]
Each time I hide/reopen it again. As Visual Studio auto open Output panel when you launch a build, it happens quite often.

**Comment by yass007** [comment]
Thanks for the extra info!
So far I'm not able to reproduce the 10sc delay between clicking on the FASTBuild Monitor tab and when it appears. For my tests I'm compiling the full Unreal Tournaments code-base and my log file contains 10000+ build events.


Is it possible for you to send me your LOG file?

**Comment by yass007** [comment]
Thanks for the extra info.

So.. I tried to reproduced the multi-seconds lag when compiling a big code-base like Unreal Tournament.
I did not get exactly that but I was able to see a small (1sc max) lag when switching between the Output tab and the Monitor one.
I'm guessing that what are you experiencing might be due to 2 things (?):
1) Your code base is generating way more events than my current worst case (Unreal). Note that Unreal has something like 11000 events (lines in the FastBuildLog.log) which can be found here C:\Users\**<your_user_name>**\AppData\Local\Temp\FastBuild
2) The CPU usage of the machine you are using is so high (when building and switching to the monitor tab) that the monitor process is completely stalled. But that seems very unlikely.

In any case these are wild guesses, it would be nice if you can send me your log so I could try with it.

That being said, I made a significant optimization pass on the monitor CPU usage in v0.95 and it should now reduced by a great factor (details in the commit description). 
So it would be awesome if you can try with the latest version and see if the lag still happens!

Cheers.

**Comment by jairbubbles** [comment]
It seems it's better now. I'll test more and keep you posted.

I attached you my last log file but I think it was not a full rebuild, I'll attach you a full log as soon as possible.

[FastBuildLog.zip](https://github.com/yass007/FASTBuildMonitor/files/449124/FastBuildLog.zip)

**Comment by jairbubbles** [comment]
After more testing it's still slow but not each time. 
 My cpu usage is 100% but I can still use my pc so it's not that bad.
![2016-09-01 17_54_41-gestionnaire des taches](https://cloud.githubusercontent.com/assets/15875066/18174281/4758e7a8-706d-11e6-9443-6cf7ae6f2da6.png)
I'm using VS2012.

**Comment by jairbubbles** [comment]
I do not have the issue with VS2015 and even when it's slow it's way better now. I'm closing the issue.
(I attached another log if you want to make some tests with it.)
[FastBuildLog.zip](https://github.com/yass007/FASTBuildMonitor/files/450182/FastBuildLog.zip)
