### ISSUE TITLE
[Suggestion] Add support for MSBuild

### ISSUE THREAD

**Issue by jairbubbles** [yass007/FASTBuildMonitor#5]
You did a fantastic job with that plugin and it would super awesome if you could add MSBuild support ;-) I know it's called "fastbuildmonitor" but fastbuild is still less used than msbuild and it could give a lot of visibility for you good work. Also it would be cool to see how msbuild is so bad compared to fastbuild.

Anyway I don't know if it's technically possible, it's just a though.

**Comment by yass007** [comment]
I have great news for you... @liamkf & I are working on supporting the MSBuild path.
We have released a first version that supports a variety of different c++ projects. 
Since it's an early version there are some limitations/requirements that we are working to minimize.

You can find it here: https://github.com/liamkf/msfastbuild

For now it's offered as a different extension as the FASTBuildMonitor. Once they are both mature and stable we'll likely merge them together into a one single FASTBuild VS integration package.

Don't hesitate to let us know about feedback/bugs if you give it a shot on your project.

**Comment by jairbubbles** [comment]
Well it's pretty awesome ! If I find time I'll try to contribute on my spare time.

**Comment by liamkf** [comment]
Haha just to note that my msfastbuild doesn't actually build using msbuild, it's still using FASTBuild to do the work! 

So if the goal was to have FASTBuildMonitor be able to visualize what msbuild is doing behind the scenes, that would be an entirely different effort. :)

**Comment by jairbubbles** [comment]
Yes I noticed that ! It's still an interesting approach.
